### ISSUE TITLE
v11 running error

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-erpnext#5]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
```
# Add this file 
# Initial db root password is 123456
# Initial login username: Administrator and login password: admin
# APP_PORT can't set 9001, otherwise container erpnext-python will be error

DB_MRAIADB_USER=root
DB_MARIADB_PASSWORD=123456
DB_MARIADB_HOST=mariadb
DB_MARIADB_PORT=3306
DB_MARIADB_VERSION=10.3

DB_REDIS_VERSION=latest

APP_VERSION=v11
APP_PORT=8000
APP_USER=Administrator
APP_PASSWORD=admin
APP_SITE_URL=erp.example.com
APP_SITE_NAME=`erp.example.com`
APP_INSTALL_APPS=erpnext
APP_CONTAINER_NAME=erpnext
APP_NETWORK=erpnext
VOLUMES_PATH_PREFIX=./volumes

LETSENCRYPT_EMAIL=email@example.com
SKIP_NGINX_TEMPLATE_GENERATION=0
```

**Comment by qiaofeng1227** [comment]
```
# Initial login username: Administrator and login password: admin
version: "3.8"

services:
  erpnext-nginx:
    image: frappe/erpnext-nginx:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-nginx
    restart: always
    ports:
      - ${APP_PORT}:80
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=${APP_PORT}
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw

  erpnext-python:
    image: frappe/erpnext-worker:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-worker
    restart: always
    environment:
      - MARIADB_HOST=${DB_MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw

  frappe-socketio:
    image: frappe/frappe-socketio:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-socketio
    restart: always
    depends_on:
      - redis-socketio
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-default:
    image: frappe/erpnext-worker:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-worker-default
    restart: always
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-short:
    image: frappe/erpnext-worker:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-worker-short
    restart: always
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-long:
    image: frappe/erpnext-worker:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-worker-long
    restart: always
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw

  erpnext-schedule:
    image: frappe/erpnext-worker:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-schedule
    restart: always
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  redis-cache:
    image: redis:${DB_REDIS_VERSION}
    container_name: ${APP_CONTAINER_NAME}-redis-cache
    restart: always
    volumes:
      - ${VOLUMES_PATH_PREFIX}/redis-cache-vol:/data

  redis-queue:
    image: redis:${DB_REDIS_VERSION}
    container_name: ${APP_CONTAINER_NAME}-redis-queue
    restart: always
    volumes:
      - ${VOLUMES_PATH_PREFIX}/redis-queue-vol:/data

  redis-socketio:
    image: redis:${DB_REDIS_VERSION}
    container_name: ${APP_CONTAINER_NAME}-redis-socketio
    restart: always
    volumes:
      - ${VOLUMES_PATH_PREFIX}/redis-socketio-vol:/data

  mariadb:
    image: mariadb:${DB_MARIADB_VERSION}
    container_name: ${APP_CONTAINER_NAME}-mariadb
    restart: always
    ports:
      - ${DB_MARIADB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_MARIADB_PASSWORD}
    volumes:
      - ./src/installation/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - ${VOLUMES_PATH_PREFIX}/mariadb-vol:/var/lib/mysql

  site-creator:
    image: frappe/erpnext-worker:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}-site-creator
    restart: "no"
    command: new
    depends_on:
      - erpnext-python
    environment:
      - SITE_NAME=${APP_SITE_URL}
      - SITES=${APP_SITE_NAME}
      - DB_ROOT_USER=${DB_MRAIADB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_MARIADB_PASSWORD}
      - ADMIN_PASSWORD=${APP_PASSWORD}
      - INSTALL_APPS=${APP_INSTALL_APPS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

volumes:
  sites-vol:
  assets-vol:
  logs-vol:

networks:
  default:
      name: "${APP_NETWORK}"
```
